{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.kr328.kaidl",
    "module": "kaidl",
    "version": "1.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kaidl-1.15.jar",
          "url": "kaidl-1.15.jar",
          "size": 59141,
          "sha512": "f1306ccfd3c16a494cb25594debd2631dd78becfaefdba5500b20016fc6a6bb8c22fe20ce38bd3b917c4e2edd58a018cb0685afb0d304c40eb30ab232272d841",
          "sha256": "830a4a0df8aaf3da4e941afe51aa969ee17c5a73b5e2d80d927a980fcbfb4d82",
          "sha1": "5d979023c5c2df6c08a3cad07721a34e9e7cb872",
          "md5": "90cddc7e1e6cf1b70f702b128f4607b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.5.30-1.0.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kaidl-1.15.jar",
          "url": "kaidl-1.15.jar",
          "size": 59141,
          "sha512": "f1306ccfd3c16a494cb25594debd2631dd78becfaefdba5500b20016fc6a6bb8c22fe20ce38bd3b917c4e2edd58a018cb0685afb0d304c40eb30ab232272d841",
          "sha256": "830a4a0df8aaf3da4e941afe51aa969ee17c5a73b5e2d80d927a980fcbfb4d82",
          "sha1": "5d979023c5c2df6c08a3cad07721a34e9e7cb872",
          "md5": "90cddc7e1e6cf1b70f702b128f4607b1"
        }
      ]
    }
  ]
}
